### ISSUE TITLE
A4 - Roadstead not populated

### ISSUE THREAD

**Issue by valefusaro** [deeper-x/shipreporting-api-dev#131]
A4 - Roadstead not populated
Ex: trip n. 17.191

**Comment by deeper-x** [comment]
Added column:
 "destination_roadstead"

**Comment by deeper-x** [comment]
please implement table

**Comment by deeper-x** [comment]
@valefusaro do you get notifications?

**Comment by valefusaro** [comment]
it works but i get no notification.
